# Generated by Django 4.2.1 on 2023-05-30 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_book', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.FileField(default='social_book/blank-profile-picture.png', upload_to='social_book/profile'),
        ),
    ]
