# Generated by Django 4.2.1 on 2023-05-31 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_book', '0005_likepost_alter_post_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowersCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.CharField(blank=True, max_length=300, null=True)),
                ('user', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
